port: 8080
env: "dev"
grpc:
  port: 6868
policy-grpc:
  port: 6869
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "docker"
  db-name: "postgres"
  ssl-mode: "disable"
log:
  level: -1
  time-format: "2006-01-02T15:04:05Z07:00"
  service-name: "auth-service"
jwt:
  issuer: "auth-service"
  expires-in: 150
  access-secret: "AS"
  refresh-secret: "RS"
