http-port: 8080
env: "dev"
clients:
  policy-client:
    host: "localhost"
    port: 6868
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "POSTGRES_PASSWORD"
  db-name: "postgres"
  ssl-mode: "disable"
log:
  level: -1
  time-format: "2006-01-02T15:04:05Z07:00"
  service-name: "auth-service"
jwt:
  issuer: "auth-service"
  expires-in: 150
  access-secret: "AS"
  refresh-secret: "RS"
redis:
  host: "localhost"
  port: 6379
  password: "123456"
  db: 0
  pool-size: 10
